using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using Object=UnityEngine.Object;
public static class BuildCorridorLoop {
 const string Art="Assets/Loop/";static Transform root;static Material wall,floor,ceiling,paint,black,light;static int meshId;
 static void Static(GameObject g){GameObjectUtility.SetStaticEditorFlags(g,StaticEditorFlags.ContributeGI|StaticEditorFlags.ReflectionProbeStatic|StaticEditorFlags.BatchingStatic);var r=g.GetComponent<MeshRenderer>();r.receiveGI=ReceiveGI.Lightmaps;r.scaleInLightmap=1;}
 static GameObject Box(string n,Vector3 p,Vector3 size,Material m,Transform parent=null,bool collider=true){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(parent?parent:root,false);g.transform.localPosition=p;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=m;if(!collider)Object.DestroyImmediate(g.GetComponent<Collider>());Static(g);return g;}
 static GameObject Surface(string n,Vector3 p,Vector2 size,Quaternion rotation,Material m,Transform parent=null,float texSize=1.2f){var g=new GameObject(n);g.transform.SetParent(parent?parent:root,false);g.transform.localPosition=p;g.transform.localRotation=rotation;float x=size.x/2,y=size.y/2;var mesh=new Mesh{name=n};mesh.vertices=new[]{new Vector3(-x,-y,0),new Vector3(-x,y,0),new Vector3(x,y,0),new Vector3(x,-y,0)};mesh.uv=new[]{Vector2.zero,new Vector2(0,size.y/texSize),size/texSize,new Vector2(size.x/texSize,0)};mesh.triangles=new[]{0,1,2,0,2,3};mesh.RecalculateNormals();mesh.RecalculateTangents();Unwrapping.GenerateSecondaryUVSet(mesh);AssetDatabase.CreateAsset(mesh,Art+"Mesh"+(meshId++)+".asset");g.AddComponent<MeshFilter>().sharedMesh=mesh;g.AddComponent<MeshRenderer>().sharedMaterial=m;Static(g);return g;}
 static Texture2D Texture(string file){string path=Art+"Signs/"+file+".png";var i=(TextureImporter)AssetImporter.GetAtPath(path);i.maxTextureSize=2048;i.anisoLevel=8;i.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Texture2D>(path);}
 static Material Print(string name,Texture2D t){var m=new Material(Shader.Find("Standard"));m.mainTexture=t;m.SetFloat("_Glossiness",.25f);AssetDatabase.CreateAsset(m,Art+name+".mat");return m;}
 static Renderer Board(string name,Vector3 pos,Vector2 size,Material m,Transform parent=null){Box(name+" frame",pos+Vector3.forward*.018f,new Vector3(size.x+.035f,size.y+.035f,.035f),paint,parent,false);var g=Surface(name,pos,size,Quaternion.identity,m,parent,1);var mesh=g.GetComponent<MeshFilter>().sharedMesh;mesh.uv=new[]{Vector2.zero,Vector2.up,Vector2.one,Vector2.right};EditorUtility.SetDirty(mesh);return g.GetComponent<Renderer>();}
 static void Connector(float x,float z){
  const float w=5.3f;Box("Connector floor backing",new Vector3(x,-.10f,z),new Vector3(w,.20f,3.4f),paint);Surface("Connector porcelain",new Vector3(x,.002f,z),new Vector2(w,3.4f),Quaternion.Euler(90,0,0),floor,null,3.6f);
  foreach(int s in new[]{-1,1}){Box("Connector wall backing",new Vector3(x,1.775f,z+s*1.8f),new Vector3(w,3.55f,.2f),paint);Surface("Connector glazed ceramic",new Vector3(x,1.775f,z+s*1.699f),new Vector2(w,3.55f),Quaternion.Euler(0,s==1?0:180,0),wall);}
  Box("Connector ceiling backing",new Vector3(x,3.58f,z),new Vector3(w,.1f,3.6f),black);
  for(int i=0;i<35;i++)Box("Connector ceiling panel",new Vector3(x-w/2+.075f+i*.15f,3.546f,z),new Vector3(.147f,.012f,3.39f),ceiling,null,false);
  var fixture=Object.Instantiate(GameObject.Find("Twin fluorescent / 4000 K"),root);fixture.name="Connector twin fluorescent";fixture.transform.SetPositionAndRotation(new Vector3(x,3.47f,z),Quaternion.Euler(0,90,0));
  var yellow=AssetDatabase.LoadAssetAtPath<Material>("Assets/ArtV2/Tactile ochre polymer.mat");if(!yellow)yellow=GameObject.Find("300 mm tactile paving").GetComponentInChildren<Renderer>().sharedMaterial;
  for(int i=0;i<17;i++){float xx=x-w/2+.15f+i*.3f;Box("Connector tactile tile",new Vector3(xx,.012f,z),new Vector3(.298f,.018f,.298f),yellow,null,false);for(int rib=0;rib<4;rib++)Box("Connector tactile rib",new Vector3(xx,.026f,z-.108f+rib*.072f),new Vector3(.26f,.009f,.025f),yellow,null,false);}
  var probe=new GameObject("Connector reflection").AddComponent<ReflectionProbe>();probe.transform.SetParent(root);probe.transform.position=new Vector3(x,1.775f,z);probe.mode=ReflectionProbeMode.Baked;probe.boxProjection=true;probe.size=new Vector3(w,3.55f,3.4f);probe.resolution=256;probe.blendDistance=1;
 }
 public static void Run(){
  EditorSceneManager.OpenScene("Assets/Scenes/Underground.unity");if(Object.FindFirstObjectByType<CorridorLoop>())throw new Exception("Loop already exists; do not rebuild over designer edits.");
  wall=AssetDatabase.LoadAssetAtPath<Material>("Assets/ArtV2/Glazed ceramic 300mm.mat");floor=AssetDatabase.LoadAssetAtPath<Material>("Assets/ArtV2/Fine aggregate porcelain 450mm.mat");ceiling=AssetDatabase.LoadAssetAtPath<Material>("Assets/ArtV3/Satin enamel aluminium.mat");paint=AssetDatabase.LoadAssetAtPath<Material>("Assets/ArtV2/Powder coated warm grey.mat");black=AssetDatabase.LoadAssetAtPath<Material>("Assets/ArtV2/Shadow and gaskets.mat");
  var remove=new[]{"Stairwell ","Stair riser backing","Porcelain tread","Porcelain riser","Anti-slip stair nosing","Invisible stair collision","Exit landing","Landing porcelain","End barrier","Continuous stainless handrail","Lower handrail","Rail bracket","Daylight entering stairwell","Stair direction"};
  foreach(var t in Object.FindObjectsByType<Transform>(FindObjectsSortMode.None)){if(t&&remove.Any(n=>t.name.StartsWith(n,StringComparison.OrdinalIgnoreCase)))Object.DestroyImmediate(t.gameObject);}
  var west=GameObject.Find("West structural wall").transform;west.localPosition=new Vector3(west.localPosition.x,west.localPosition.y,14.7f);west.localScale=new Vector3(west.localScale.x,west.localScale.y,26.6f);
  var ceramic=GameObject.Find("West glazed ceramic").transform;ceramic.localPosition=new Vector3(ceramic.localPosition.x,ceramic.localPosition.y,14.7f);var filter=ceramic.GetComponent<MeshFilter>();var clone=Object.Instantiate(filter.sharedMesh);var vs=clone.vertices;var uv=clone.uv;for(int i=0;i<vs.Length;i++){vs[i].x*=26.6f/30;uv[i].x*=26.6f/30;}clone.vertices=vs;clone.uv=uv;clone.RecalculateBounds();Unwrapping.GenerateSecondaryUVSet(clone);AssetDatabase.CreateAsset(clone,Art+"WestWallWithEntry.asset");filter.sharedMesh=clone;
  foreach(var t in Object.FindObjectsByType<Transform>(FindObjectsSortMode.None))if(t.name=="Recessed skirting"&&t.position.x<0){t.localPosition=new Vector3(t.localPosition.x,t.localPosition.y,14.7f);t.localScale=new Vector3(t.localScale.x,t.localScale.y,26.6f);}
  root=new GameObject("LOOP / concealed return corridors").transform;Connector(-4.85f,-.3f);Connector(4.85f,26.3f);
  foreach(var p in new[]{new Vector3(-7.6f,1.775f,-.3f),new Vector3(7.6f,1.775f,26.3f)}){Box("Portal corridor end backing",p,new Vector3(.2f,3.55f,3.6f),paint);Surface("Portal corridor end ceramic",p+Vector3.right*(p.x<0?.101f:-.101f),new Vector2(3.4f,3.55f),Quaternion.Euler(0,p.x<0?-90:90,0),wall);}
  var numbers=new Texture2D[9];for(int i=0;i<9;i++)numbers[i]=Texture("Exit"+i);var numberMat=Print("Loop progress sign",numbers[0]);var rules=Print("Loop instructions",Texture("Rules"));
  var signs=new System.Collections.Generic.List<Renderer>();signs.Add(Board("Entry progress",new Vector3(-4.8f,2.60f,1.391f),new Vector2(1.8f,.30f),numberMat));Board("Entry instructions",new Vector3(-4.8f,1.48f,1.39f),new Vector2(1.25f,1.25f),rules);
  signs.Add(Board("Return progress",new Vector3(4.8f,2.6f,27.991f),new Vector2(1.8f,.30f),numberMat));Board("Return instructions",new Vector3(4.8f,1.48f,27.99f),new Vector2(1.25f,1.25f),rules);
  foreach(var r in GameObject.Find("Illuminated exit wayfinding").GetComponentsInChildren<Renderer>())if(r.name.Contains("face")){signs.Add(r);}
  var win=new GameObject("FINAL EXIT / unlocked after eight decisions");win.transform.SetParent(root);win.transform.position=new Vector3(30,0,0);var wt=win.transform;
  Box("Final exit floor",new Vector3(0,-.1f,4),new Vector3(4,.2f,10),paint,wt);Surface("Final exit porcelain",new Vector3(0,.002f,4),new Vector2(4,10),Quaternion.Euler(90,0,0),floor,wt,3.6f);
  foreach(int s in new[]{-1,1}){Box("Final exit wall",new Vector3(s*2.1f,1.775f,4),new Vector3(.2f,3.55f,10),paint,wt);Surface("Final exit ceramic",new Vector3(s*1.999f,1.775f,4),new Vector2(10,3.55f),Quaternion.Euler(0,s==1?90:-90,0),wall,wt);}
  Box("Final exit ceiling",new Vector3(0,3.55f,4),new Vector3(4,.06f,10),ceiling,wt);Box("Final exit back wall",new Vector3(0,1.775f,-1.1f),new Vector3(4,3.55f,.2f),paint,wt);
  light=new Material(Shader.Find("Standard"));light.color=Color.white;light.EnableKeyword("_EMISSION");light.SetColor("_EmissionColor",new Color(1,.96f,.83f)*3);light.globalIlluminationFlags=MaterialGlobalIlluminationFlags.BakedEmissive;AssetDatabase.CreateAsset(light,Art+"Daylit exit.mat");Box("Daylit exit portal",new Vector3(0,1.6f,8),new Vector3(3,3.2f,.04f),light,wt);
  signs.Add(Board("Final number eight",new Vector3(0,2.7f,5.7f),new Vector2(2.4f,.36f),numberMat,wt));
  var finalFixture=Object.Instantiate(GameObject.Find("Twin fluorescent / 4000 K"),wt);finalFixture.transform.localPosition=new Vector3(0,3.47f,3);
  var game=new GameObject("OYUN / koridor döngüsü").AddComponent<CorridorLoop>();game.player=Object.FindFirstObjectByType<FirstPerson>();game.posters=Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).Where(t=>t.name.StartsWith("Printed advertisement")).OrderBy(t=>t.position.z).Select(t=>t.gameObject).ToArray();game.vent=Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).First(t=>t.name=="Wall ventilation grille").gameObject;game.door=Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).First(t=>t.name.StartsWith("Recessed utility door")).gameObject;game.sign=GameObject.Find("Illuminated exit wayfinding");game.cctv=GameObject.Find("Smoked CCTV hemisphere");game.tactileSection=Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).Where(t=>t.name=="300 mm tactile paving"&&t.position.z>10&&t.position.z<13).Select(t=>t.gameObject).ToArray();game.lightTubes=Object.FindObjectsByType<Renderer>(FindObjectsSortMode.None).Where(r=>r.name=="T8 26 mm phosphor tube"&&r.transform.position.z>7&&r.transform.position.z<12).ToArray();game.accentLight=Object.FindObjectsByType<Light>(FindObjectsSortMode.None).First(l=>l.name=="Realtime specular support"&&l.transform.position.z>7);game.numberSigns=signs.ToArray();game.numberTextures=numbers;game.exitRoom=win;
  game.player.Teleport(new Vector3(-4.8f,.04f,-.3f),90,true);
  var look=Object.FindFirstObjectByType<StationLookControls>();look.lights=Object.FindObjectsByType<Light>(FindObjectsSortMode.None);look.probes=Object.FindObjectsByType<ReflectionProbe>(FindObjectsSortMode.None);look.Apply();
  Save();if(!Lightmapping.Bake())throw new Exception("Loop bake failed");Save();StationImportedModels.Capture();BuildStation.BuildPlayer();Debug.Log("STATION_LOOP_BUILD_COMPLETE");
 }
 static void Save(){EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());AssetDatabase.SaveAssets();}
 public static void Open(){EditorSceneManager.OpenScene("Assets/Scenes/Underground.unity");Selection.activeGameObject=GameObject.Find("OYUN / koridor döngüsü");}
 public static void Export(){EditorSceneManager.OpenScene("Assets/Scenes/Underground.unity");var c=Camera.main;var p=c.transform.position;var q=c.transform.rotation;Shot(c,"loop-entry",new Vector3(-5.3f,1.67f,-1.05f),Quaternion.Euler(0,25,0));Shot(c,"loop-return",new Vector3(.3f,1.67f,24.9f),Quaternion.Euler(0,65,0));c.transform.SetPositionAndRotation(p,q);BuildStation.BuildPlayer();Debug.Log("STATION_LOOP_FINAL_EXPORT");}
 static void Shot(Camera c,string name,Vector3 p,Quaternion q){c.transform.SetPositionAndRotation(p,q);var rt=new RenderTexture(1920,1080,24,RenderTextureFormat.ARGBHalf);rt.Create();c.targetTexture=rt;for(int i=0;i<20;i++)c.Render();RenderTexture.active=rt;var t=new Texture2D(1920,1080,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1920,1080),0,0);var pixels=t.GetPixels();for(int i=0;i<pixels.Length;i++)pixels[i]=pixels[i].gamma;t.SetPixels(pixels);t.Apply();File.WriteAllBytes("Screenshots/"+name+".png",t.EncodeToPNG());c.targetTexture=null;RenderTexture.active=null;Object.DestroyImmediate(t);Object.DestroyImmediate(rt);}
}
