using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using System.IO;
public static class BuildStation {
    static Material wall,floor,steel,dark,yellow,white,ceiling; static Font font; static Transform root;
    static Material Mat(string name,Color c,float metallic=0,float gloss=.4f){var m=new Material(Shader.Find("Standard"));m.color=c;m.SetFloat("_Metallic",metallic);m.SetFloat("_Glossiness",gloss);AssetDatabase.CreateAsset(m,"Assets/Materials/"+name+".mat");return m;}
    static GameObject Box(string name,Vector3 p,Vector3 size,Material mat,Transform parent=null){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=name;g.transform.SetParent(parent?parent:root,false);g.transform.localPosition=p;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;g.isStatic=true;return g;}
    static void Rod(string name,Vector3 a,Vector3 b,float radius,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cylinder);g.name=name;g.transform.SetParent(root);g.transform.position=(a+b)/2;g.transform.up=(b-a).normalized;g.transform.localScale=new Vector3(radius*2,(b-a).magnitude/2,radius*2);g.GetComponent<Renderer>().sharedMaterial=mat;Object.DestroyImmediate(g.GetComponent<Collider>());g.isStatic=true;}
    static void Text(Transform parent,string value,Vector3 p,float size,Color c,TextAnchor anchor=TextAnchor.MiddleCenter){var g=new GameObject("Lettering");g.transform.SetParent(parent,false);g.transform.localPosition=p;var t=g.AddComponent<TextMesh>();t.text=value;t.font=font;t.fontSize=80;t.characterSize=size*.12f;t.anchor=anchor;t.alignment=TextAlignment.Center;t.color=c;t.GetComponent<Renderer>().sharedMaterial=font.material;}
    static Transform Panel(string name,Vector3 p,Vector2 size,float angle,Material mat){var g=new GameObject(name);g.transform.SetParent(root);g.transform.position=p;g.transform.rotation=Quaternion.Euler(0,angle,0);Box("Brushed frame",Vector3.zero,new Vector3(size.x+.06f,size.y+.06f,.065f),steel,g.transform);Box("Printed face",new Vector3(0,0,-.038f),new Vector3(size.x,size.y,.012f),mat,g.transform);return g.transform;}
    static void LightAt(Vector3 p,float intensity,float range,Color color,bool shadow){var g=new GameObject("Fluorescent bounce");g.transform.SetParent(root);g.transform.position=p;var l=g.AddComponent<Light>();l.type=LightType.Point;l.color=color;l.intensity=intensity;l.range=range;l.shadows=shadow?LightShadows.Soft:LightShadows.None;l.shadowStrength=.7f;l.shadowBias=.035f;}
    public static void Build(){
        Directory.CreateDirectory("Assets/Materials");Directory.CreateDirectory("Assets/Scenes");Directory.CreateDirectory("Screenshots");
        EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);root=new GameObject("EXIT 7  Underground passage").transform;
        font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        wall=new Material(Shader.Find("Exit7/Ceramic"));wall.SetColor("_Color",new Color(.69f,.72f,.70f));wall.SetFloat("_Size",.3f);AssetDatabase.CreateAsset(wall,"Assets/Materials/Ceramic.mat");
        floor=new Material(wall);floor.SetColor("_Color",new Color(.49f,.52f,.50f));floor.SetFloat("_Size",.45f);floor.SetFloat("_Gloss",.32f);AssetDatabase.CreateAsset(floor,"Assets/Materials/Floor.mat");
        steel=Mat("Brushed steel",new Color(.38f,.41f,.40f),.78f,.65f);dark=Mat("Graphite",new Color(.065f,.075f,.07f),.25f,.35f);
        yellow=Mat("Tactile ochre",new Color(.72f,.52f,.15f),0,.28f);ceiling=Mat("Ceiling enamel",new Color(.51f,.54f,.52f),.25f,.5f);
        white=Mat("Tube phosphor",Color.white);white.EnableKeyword("_EMISSION");white.SetColor("_EmissionColor",new Color(.79f,.88f,1)*3);
        var sign=Mat("Warm illuminated sign",new Color(.96f,.78f,.24f));sign.EnableKeyword("_EMISSION");sign.SetColor("_EmissionColor",new Color(.9f,.68f,.13f)*.7f);
        Box("Foundation",new Vector3(0,-.16f,15),new Vector3(5.4f,.3f,34),floor);
        Box("West tiled wall",new Vector3(-2.6f,1.8f,15),new Vector3(.2f,3.6f,34),wall);
        Box("East tiled wall",new Vector3(2.6f,1.8f,15),new Vector3(.2f,3.6f,34),wall);
        Box("Entrance back wall",new Vector3(0,1.8f,-2),new Vector3(5.4f,3.6f,.2f),wall);
        Box("Ceiling",new Vector3(0,3.66f,15),new Vector3(5.4f,.16f,34),ceiling);
        for(int i=0;i<114;i++)Box("Ceiling panel seam",new Vector3(0,3.57f,-2+i*.3f),new Vector3(5.05f,.012f,.009f),dark);
        for(int side=-1;side<=1;side+=2)Box("Stone skirting",new Vector3(side*2.485f,.065f,15),new Vector3(.035f,.13f,34),floor);
        // Raised directional paving is actual geometry, so the grazing light catches the ribs.
        for(int i=0;i<74;i++){float z=-1.5f+i*.45f;Box("Tactile paving",new Vector3(0,.008f,z),new Vector3(.44f,.025f,.44f),yellow);for(int j=0;j<5;j++)Box("Raised guide rib",new Vector3(-.16f+j*.08f,.027f,z),new Vector3(.026f,.018f,.35f),yellow);}
        for(int i=0;i<8;i++){float z=1+i*4.1f;Box("Luminaire housing",new Vector3(0,3.49f,z),new Vector3(1.56f,.13f,.25f),steel);for(int j=-1;j<=1;j+=2)Box("Fluorescent tube",new Vector3(0,3.407f,z+j*.067f),new Vector3(1.40f,.045f,.038f),white);LightAt(new Vector3(0,3.10f,z),1.65f,6.1f,new Color(.88f,.94f,1),i%2==0);}
        var overhead=Panel("EXIT 7 suspended direction sign",new Vector3(0,2.94f,5),new Vector2(3.3f,.40f),0,sign);Text(overhead,"  EXIT  7",new Vector3(0,0,-.052f),.22f,Color.black);
        Rod("Sign hanger",new Vector3(-1.3f,3.55f,5),new Vector3(-1.3f,3.16f,5),.012f,steel);Rod("Sign hanger",new Vector3(1.3f,3.55f,5),new Vector3(1.3f,3.16f,5),.012f,steel);
        string[] titles={"WITH A SMILE","MAKE ROOM","NIGHT / SOUND","A QUIETER CITY","LOOK CLOSER","MOVE FEST"};
        string[] bodies={"DENTAL CLINIC\n\n08 / 08  OPEN","ART & PHOTOGRAPHY\n\n12.15  12.17","UNDERGROUND SESSIONS\n\nFRIDAY  20:00","PUBLIC TRANSPORT\n\nEVERY DAY. TOGETHER.","PHOTO EXHIBITION\n\nGALLERY 07","LIVE MUSIC\n\n09.24   /   19:30"};
        Color[] colors={new Color(.62f,.18f,.15f),new Color(.20f,.47f,.51f),new Color(.12f,.16f,.29f),new Color(.69f,.47f,.18f),new Color(.57f,.37f,.40f),new Color(.23f,.32f,.23f)};
        for(int i=0;i<6;i++){var ink=Mat("Poster "+i,colors[i]);var paper=Mat("Paper "+i,new Color(.80f,.79f,.71f));var p=Panel("Framed station advertisement "+i,new Vector3(-2.46f,1.89f,3.5f+i*3.7f),new Vector2(.95f,1.42f),-90,paper);Box("Color block",new Vector3(0,.33f,-.049f),new Vector3(.93f,.72f,.008f),ink,p);Text(p,titles[i],new Vector3(0,.54f,-.06f),.063f,Color.white);Text(p,i%2==0?"07":"/ / /",new Vector3(0,.22f,-.061f),.30f,Color.white);Text(p,bodies[i],new Vector3(0,-.19f,-.06f),.043f,colors[i]);Text(p,"METRO CULTURE   /   EXIT 7",new Vector3(0,-.61f,-.06f),.025f,colors[i]);}
        var door=Mat("Service door paint",new Color(.40f,.45f,.44f),.3f,.38f);
        for(int i=0;i<3;i++){float z=9+i*7;Box("Service door surround",new Vector3(2.46f,1.13f,z),new Vector3(.10f,2.26f,1.04f),steel);Box("Recessed service door",new Vector3(2.395f,1.10f,z),new Vector3(.045f,2.16f,.91f),door);Box("Door handle",new Vector3(2.345f,1.02f,z-.32f),new Vector3(.065f,.045f,.15f),steel);var p=Panel("Staff only plaque",new Vector3(2.36f,1.68f,z),new Vector2(.36f,.15f),90,dark);Text(p,"STAFF ONLY",new Vector3(0,0,-.05f),.035f,Color.white);}
        for(int i=0;i<5;i++){float z=4+i*6;Box("Vent frame",new Vector3(2.465f,2.89f,z),new Vector3(.07f,.43f,.65f),steel);Box("Vent darkness",new Vector3(2.42f,2.89f,z),new Vector3(.025f,.37f,.59f),dark);for(int j=0;j<7;j++)Box("Vent louvre",new Vector3(2.397f,2.73f+j*.051f,z),new Vector3(.045f,.018f,.58f),steel);}
        var notice=Panel("Surveillance notice",new Vector3(2.46f,1.8f,5.8f),new Vector2(.65f,.75f),90,Mat("Notice paper",new Color(.84f,.84f,.79f)));Text(notice,"CCTV",new Vector3(0,.18f,-.06f),.16f,Color.black);Text(notice,"SECURITY CAMERAS\nIN OPERATION",new Vector3(0,-.13f,-.06f),.048f,new Color(.4f,.09f,.06f));
        for(int i=0;i<3;i++){float z=6+i*10;var c=GameObject.CreatePrimitive(PrimitiveType.Sphere);c.name="CCTV smoked dome";c.transform.SetParent(root);c.transform.position=new Vector3(-1.9f,3.43f,z);c.transform.localScale=new Vector3(.20f,.18f,.20f);c.GetComponent<Renderer>().sharedMaterial=dark;}
        // Exit staircase, with a smooth collision ramp for a stable first-person ascent.
        for(int i=0;i<22;i++){float z=32+i*.31f;var step=Box("Exit stair "+(i+1),new Vector3(0,i*.16f+.075f,z),new Vector3(5,.16f,.31f),floor);Object.DestroyImmediate(step.GetComponent<Collider>());Box("Stair nosing",new Vector3(0,i*.16f+.157f,z-.135f),new Vector3(4.98f,.014f,.035f),steel);}
        var ramp=new GameObject("Invisible stair collision");ramp.transform.SetParent(root);var mesh=new Mesh();mesh.vertices=new[]{new Vector3(-2.5f,0,31.8f),new Vector3(2.5f,0,31.8f),new Vector3(-2.5f,3.55f,38.75f),new Vector3(2.5f,3.55f,38.75f)};mesh.triangles=new[]{0,2,1,1,2,3};mesh.RecalculateNormals();AssetDatabase.CreateAsset(mesh,"Assets/Materials/StairCollision.asset");ramp.AddComponent<MeshCollider>().sharedMesh=mesh;
        for(int side=-1;side<=1;side+=2){Box("Stairwell tile wall",new Vector3(side*2.6f,3.5f,35.5f),new Vector3(.2f,7,7),wall);Rod("Continuous stair handrail",new Vector3(side*2.30f,1.03f,31.5f),new Vector3(side*2.30f,4.58f,38.5f),.033f,steel);for(int i=0;i<5;i++)Rod("Handrail wall bracket",new Vector3(side*2.48f,1+i*.70f,32+i*1.4f),new Vector3(side*2.30f,1+i*.70f,32+i*1.4f),.015f,steel);}
        Box("Exit landing",new Vector3(0,3.42f,40),new Vector3(5,.2f,3),floor);Box("Daylit exit",new Vector3(0,5.2f,41.4f),new Vector3(5,3.6f,.15f),white);Box("Stairwell ceiling",new Vector3(0,7.05f,36.5f),new Vector3(5.4f,.2f,10),ceiling);LightAt(new Vector3(0,5.5f,37),4,11,new Color(.91f,.96f,1),true);
        var destination=Panel("Stairs wayfinding",new Vector3(-2.46f,1.7f,29.5f),new Vector2(.85f,1.4f),-90,sign);Text(destination,"EXIT\n7  \n\nNORTH SQUARE\nCITY PARK",new Vector3(0,0,-.06f),.09f,Color.black);
        RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Trilight;RenderSettings.ambientSkyColor=new Color(.28f,.31f,.34f);RenderSettings.ambientEquatorColor=new Color(.16f,.18f,.19f);RenderSettings.ambientGroundColor=new Color(.09f,.10f,.10f);RenderSettings.fog=true;RenderSettings.fogColor=new Color(.43f,.48f,.49f);RenderSettings.fogMode=FogMode.ExponentialSquared;RenderSettings.fogDensity=.008f;
        var player=new GameObject("Player  WASD + mouse");player.transform.position=new Vector3(.65f,.08f,.2f);var cc=player.AddComponent<CharacterController>();cc.height=1.8f;cc.center=new Vector3(0,.9f,0);cc.radius=.23f;cc.stepOffset=.25f;cc.slopeLimit=50;cc.skinWidth=.025f;
        var cg=new GameObject("First person camera");cg.tag="MainCamera";cg.transform.SetParent(player.transform,false);cg.transform.localPosition=new Vector3(0,1.67f,0);var cam=cg.AddComponent<Camera>();cam.fieldOfView=68;cam.nearClipPlane=.04f;cam.farClipPlane=100;cam.allowHDR=true;cam.allowMSAA=true;cam.renderingPath=RenderingPath.Forward;cam.clearFlags=CameraClearFlags.SolidColor;cam.backgroundColor=RenderSettings.fogColor;cg.AddComponent<AudioListener>();player.AddComponent<FirstPerson>().view=cam;
        var film=new Material(Shader.Find("Exit7/Film"));AssetDatabase.CreateAsset(film,"Assets/Materials/Film.mat");cg.AddComponent<FilmEffect>().material=film;
        QualitySettings.SetQualityLevel(QualitySettings.names.Length-1);QualitySettings.pixelLightCount=12;QualitySettings.shadows=ShadowQuality.All;QualitySettings.shadowResolution=ShadowResolution.High;QualitySettings.shadowDistance=45;QualitySettings.antiAliasing=4;QualitySettings.vSyncCount=1;
        PlayerSettings.colorSpace=ColorSpace.Linear;PlayerSettings.companyName="Onur";PlayerSettings.productName="Exit 7";PlayerSettings.defaultScreenWidth=1600;PlayerSettings.defaultScreenHeight=900;PlayerSettings.fullScreenMode=FullScreenMode.Windowed;
        EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene(),"Assets/Scenes/Underground.unity");EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/Scenes/Underground.unity",true)};AssetDatabase.SaveAssets();
        OpenStation.Validate(); Screenshot(cam,"Screenshots/corridor.png");File.WriteAllText("BUILD_READY.txt","Scene generated successfully.");Debug.Log("EXIT7_BUILD_SUCCESS");
    }
    static void Screenshot(Camera cam,string path){var rt=new RenderTexture(1600,900,24,RenderTextureFormat.ARGB32);cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;var tex=new Texture2D(1600,900,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1600,900),0,0);tex.Apply();File.WriteAllBytes(path,tex.EncodeToPNG());cam.targetTexture=null;RenderTexture.active=null;Object.DestroyImmediate(rt);Object.DestroyImmediate(tex);}
    public static void BuildPlayer(){BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/Scenes/Underground.unity"},locationPathName="Build/Exit7.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.None});}
}

