using System;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using Object=UnityEngine.Object;
public static class CommuterAndSurgeSetup {
 const string Folder="Assets/Commuter/";
 static Material Surface(string name,string suffix,float gloss){var m=new Material(Shader.Find("Standard")){name=name,color=Color.white};m.mainTexture=AssetDatabase.LoadAssetAtPath<Texture2D>(Folder+"m014_"+suffix+"_color.tga");m.SetFloat("_Glossiness",gloss);var n=AssetDatabase.LoadAssetAtPath<Texture2D>(Folder+"m014_"+suffix+"_normal.tga");if(n){m.SetTexture("_BumpMap",n);m.EnableKeyword("_NORMALMAP");m.SetFloat("_BumpScale",.6f);}AssetDatabase.CreateAsset(m,Folder+name+".mat");return m;}
 public static void Run(){
  var scene=EditorSceneManager.OpenScene("Assets/Scenes/Underground.unity");var loop=Object.FindFirstObjectByType<CorridorLoop>();
  var oldTiles=Object.FindObjectsByType<MeshFilter>(FindObjectsSortMode.None).Where(f=>f.name=="Tactile route tile").ToArray();var straight=oldTiles.First(f=>f.transform.localPosition.z>2&&f.transform.localPosition.z<20).sharedMesh;var corner=oldTiles.First(f=>Mathf.Abs(f.transform.localPosition.x)<.01f&&f.transform.localPosition.z<0).sharedMesh;var yellow=oldTiles[0].GetComponent<Renderer>().sharedMaterial;
  foreach(var root in Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).Where(t=>t&&t.name.StartsWith("Guide passage ")).ToArray()){foreach(var tile in root.GetComponentsInChildren<MeshFilter>())Object.DestroyImmediate(tile.gameObject);
   for(int i=1;i<59;i++)Tile(root,straight,yellow,new Vector3(0,.015f,-.3f+i*26.6f/59),0,new Vector3(.448f/.298f,1,(26.6f/59-.002f)/.298f));
   foreach(int side in new[]{-1,1}){float z=side<0?-.3f:26.3f;Tile(root,corner,yellow,new Vector3(0,.015f,z),0,new Vector3(.448f/.298f,1,.448f/.298f));float step=5.975f/13;for(int i=0;i<13;i++)Tile(root,straight,yellow,new Vector3(side*(.225f+(i+.5f)*step),.015f,z),90,new Vector3(.448f/.298f,1,(step-.002f)/.298f));}
  }
  var mainGuide=GameObject.Find("Guide passage 0");loop.tactileSection=mainGuide.GetComponentsInChildren<MeshFilter>().Where(f=>f.transform.localPosition.z>10&&f.transform.localPosition.z<13).Select(f=>f.gameObject).ToArray();
  var npc=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(Folder+"Male_Adult_08.fbx"));npc.name="Commuter / man with briefcase";var body=Surface("Blue cotton shirt","body",.23f);var head=Surface("Natural skin","head",.31f);var opacity=Surface("Hair and eyelashes","opacity",.15f);opacity.SetFloat("_Mode",1);opacity.SetFloat("_Cutoff",.35f);opacity.EnableKeyword("_ALPHATEST_ON");opacity.renderQueue=2450;
  foreach(var r in npc.GetComponentsInChildren<SkinnedMeshRenderer>()){var mats=r.sharedMaterials;for(int i=0;i<mats.Length;i++)mats[i]=mats[i].name.Contains("head")?head:mats[i].name.Contains("opacity")?opacity:body;r.sharedMaterials=mats;r.updateWhenOffscreen=true;}
  var source=AssetDatabase.LoadAllAssetsAtPath(Folder+"m_walk_neutral.max.fbx").OfType<AnimationClip>().First(c=>!c.name.StartsWith("__"));var walk=Object.Instantiate(source);walk.name="Walk";walk.legacy=true;walk.wrapMode=WrapMode.Loop;AssetDatabase.CreateAsset(walk,Folder+"Walk.anim");var animation=npc.GetComponent<Animation>();if(!animation)animation=npc.AddComponent<Animation>();animation.clip=walk;animation.AddClip(walk,"Walk");animation.playAutomatically=false;animation.cullingType=AnimationCullingType.AlwaysAnimate;
  var motor=npc.AddComponent<CharacterController>();motor.height=1.78f;motor.radius=.23f;motor.center=new Vector3(0,.91f,0);motor.skinWidth=.025f;motor.stepOffset=.15f;
  var audio=npc.AddComponent<AudioSource>();audio.playOnAwake=false;audio.spatialBlend=1;audio.minDistance=1;audio.maxDistance=14;audio.dopplerLevel=0;audio.volume=.5f;
  var driver=npc.AddComponent<StationCommuter>();driver.player=loop.player;driver.walking=animation;driver.hips=npc.transform.Find("Bip01");driver.rightHand=npc.GetComponentsInChildren<Transform>().First(t=>t.name=="Bip01 R Hand");driver.footsteps=loop.player.GetComponent<StationFootsteps>().clips;
  var bag=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(Folder+"Briefcase.fbx"),npc.transform);bag.name="Leather commuter briefcase";driver.briefcase=bag.transform;var leather=new Material(Shader.Find("Standard")){color=new Color(.024f,.020f,.018f)};leather.SetFloat("_Glossiness",.36f);AssetDatabase.CreateAsset(leather,Folder+"Black leather.mat");var metal=new Material(Shader.Find("Standard")){color=new Color(.32f,.33f,.34f)};metal.SetFloat("_Metallic",.85f);metal.SetFloat("_Glossiness",.55f);AssetDatabase.CreateAsset(metal,Folder+"Bag fittings.mat");foreach(var r in bag.GetComponentsInChildren<Renderer>())r.sharedMaterial=r.name.Contains("Metal")||r.name.Contains("Zipper")?metal:leather;loop.commuter=driver;driver.ResetRoute();animation["Walk"].time=.18f;animation.Sample();bag.transform.position=driver.rightHand.position-Vector3.up*.205f+npc.transform.right*.035f;bag.transform.rotation=npc.transform.rotation;
  var h=loop.horror;h.floodSpeed=5.5f;h.floodTriggerZ=11.5f;h.floodWarningSeconds=1.2f;h.water.SetActive(false);var waterMat=h.water.GetComponent<Renderer>().sharedMaterial;waterMat.SetVector("_FlowAxis",new Vector4(0,1,0,0));waterMat.SetFloat("_Rise",1.25f);waterMat.SetFloat("_Crest",.85f);EditorUtility.SetDirty(waterMat);
  h.entryWater=Object.Instantiate(h.water);h.entryWater.name="Flood / hidden corner source";var entryMat=new Material(waterMat);entryMat.SetVector("_FlowAxis",new Vector4(1,0,0,0));AssetDatabase.CreateAsset(entryMat,"Assets/Loop/CornerSurge.mat");h.entryWater.GetComponent<Renderer>().sharedMaterial=entryMat;h.entryWater.SetActive(false);
  var mist=new GameObject("Flood / airborne spray");var ps=mist.AddComponent<ParticleSystem>();var main=ps.main;main.playOnAwake=false;main.loop=true;main.startLifetime=new ParticleSystem.MinMaxCurve(.35f,.85f);main.startSpeed=new ParticleSystem.MinMaxCurve(.7f,2.2f);main.startSize=new ParticleSystem.MinMaxCurve(.08f,.28f);main.gravityModifier=.55f;main.maxParticles=450;main.simulationSpace=ParticleSystemSimulationSpace.World;var shape=ps.shape;shape.shapeType=ParticleSystemShapeType.Box;shape.scale=new Vector3(4.2f,.24f,.35f);var emission=ps.emission;emission.rateOverTime=160;var velocity=ps.velocityOverLifetime;velocity.enabled=true;velocity.space=ParticleSystemSimulationSpace.World;velocity.y=new ParticleSystem.MinMaxCurve(.8f,1.6f);velocity.z=new ParticleSystem.MinMaxCurve(-2.8f,-1.2f);velocity.x=new ParticleSystem.MinMaxCurve(-.4f,.4f);
  var color=ps.colorOverLifetime;color.enabled=true;var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(new Color(.72f,.79f,.79f),0),new GradientColorKey(new Color(.80f,.84f,.84f),1)},new[]{new GradientAlphaKey(0,0),new GradientAlphaKey(.25f,.15f),new GradientAlphaKey(0,1)});color.color=gradient;
  var texture=new Texture2D(64,64,TextureFormat.RGBA32,false);for(int y=0;y<64;y++)for(int x=0;x<64;x++){float d=Vector2.Distance(new Vector2(x,y),new Vector2(31.5f,31.5f))/31.5f;texture.SetPixel(x,y,new Color(1,1,1,Mathf.Pow(Mathf.Clamp01(1-d*d),3)));}texture.Apply();AssetDatabase.CreateAsset(texture,"Assets/Loop/SpraySoftness.asset");var spray=new Material(Shader.Find("Particles/Standard Unlit"));spray.mainTexture=texture;spray.SetFloat("_Mode",2);spray.SetInt("_SrcBlend",(int)BlendMode.SrcAlpha);spray.SetInt("_DstBlend",(int)BlendMode.OneMinusSrcAlpha);spray.SetInt("_ZWrite",0);spray.EnableKeyword("_ALPHABLEND_ON");spray.renderQueue=3001;AssetDatabase.CreateAsset(spray,"Assets/Loop/FloodSpray.mat");ps.GetComponent<ParticleSystemRenderer>().sharedMaterial=spray;ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);h.floodSpray=ps;
  EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();if(!Lightmapping.Bake())throw new Exception("Wide guide bake failed");EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();BuildCorridorLoop.Export();Debug.Log("COMMUTER_SURGE_READY");
 }
 static void Tile(Transform root,Mesh mesh,Material mat,Vector3 p,float yaw,Vector3 scale){var g=new GameObject("Tactile route tile");g.transform.SetParent(root,false);g.transform.localPosition=p;g.transform.localRotation=Quaternion.Euler(0,yaw,0);g.transform.localScale=scale;g.AddComponent<MeshFilter>().sharedMesh=mesh;var r=g.AddComponent<MeshRenderer>();r.sharedMaterial=mat;GameObjectUtility.SetStaticEditorFlags(g,StaticEditorFlags.ContributeGI|StaticEditorFlags.ReflectionProbeStatic|StaticEditorFlags.BatchingStatic);r.receiveGI=ReceiveGI.Lightmaps;r.scaleInLightmap=3;}
}
